version: "3.9"

services:
  api:
    build: .
    container_name: api
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/mydb?createDatabaseIfNotExist=true
      DATABASE_USERNAME: db_user
      DATABASE_PASSWORD: db_password
      DDL_AUTO: create
      SHOW_SQL: "true"
      SQL_PLATFORM: mysql
      CHAR_SET: UTF-8
      PORT: 8080

    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: db_root_password
    ports:
      - "3306:3306"
